### ISSUE TITLE
OmniSR variable passing bug.

### ISSUE THREAD

**Issue by Sirosky** [muslll/neosr#2]
I was training a 2x OmniSR model, and encountered the following error:

```
Traceback (most recent call last):
  File "D:\Users\Sirosky\Jottacloud\Media\Upscaling\Trainers\neosr\train.py", line 238, in <module>
    train_pipeline(root_path)
  File "D:\Users\Sirosky\Jottacloud\Media\Upscaling\Trainers\neosr\train.py", line 139, in train_pipeline
    model = build_model(opt)
  File "D:\Users\Sirosky\Jottacloud\Media\Upscaling\Trainers\neosr\neosr\models\__init__.py", line 28, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "D:\Users\Sirosky\Jottacloud\Media\Upscaling\Trainers\neosr\neosr\models\default.py", line 35, in __init__
    self.net_g = build_network(opt['network_g'])
  File "D:\Users\Sirosky\Jottacloud\Media\Upscaling\Trainers\neosr\neosr\archs\__init__.py", line 21, in build_network
    net = ARCH_REGISTRY.get(network_type)(**opt)
  File "D:\Users\Sirosky\Jottacloud\Media\Upscaling\Trainers\neosr\neosr\archs\omnisr_arch.py", line 883, in omnisr
    return omnisr_net(
  File "D:\Users\Sirosky\Jottacloud\Media\Upscaling\Trainers\neosr\neosr\archs\omnisr_arch.py", line 834, in __init__
    up_scale    = kwargs["upsampling"]
KeyError: 'upsampling'
```

These were my `network_g` settings:

`
network_g:
  type: omnisr 
  upsampling: 2
  window_size: 16
`

------------

It seems like the solution to fixing this is to revise like 830 of `omnisr_arch.py` from:

`def __init__(self,num_in_ch=3,num_out_ch=3,num_feat=64, window_size=8, upsampling=4, **kwargs):`

to 

`def __init__(self,num_in_ch=3,num_out_ch=3,num_feat=64, **kwargs):`

Might be easiest to require `window_size` and `upsampling` to be specified in the config.

**Comment by muslll** [comment]
Thanks for reporting. I [commited](https://github.com/muslll/neosr/commit/656f63c2b2cf93c6927a08418bf4e7b12289d29e) a temporary fix for now, but I'll take a look to make the param parsing better.
