### ISSUE TITLE
can not start train

### ISSUE THREAD

**Issue by linkhins122** [muslll/neosr#80]
PS D:\AIGC\Net-Train\neosr-new> python train.py -opt train_compact.yml
Path already exists. Renaming it to D:\AIGC\Net-Train\neosr-new\experiments\2xFilm_archived_20240622_233806
Path already exists. Renaming it to D:\AIGC\Net-Train\neosr-new\experiments\tb_logger\2xFilm_archived_20240622_233806
22-06-2024 11:38 PM | INFO:
------------------------ neosr ------------------------
Pytorch Version: 2.3.1+cu121
22-06-2024 11:38 PM | INFO: Dataset [paired] is built.
22-06-2024 11:38 PM | INFO: Training statistics:
        Starting model: 2xFilm
        Number of train images: 200
        Dataset enlarge ratio: 1
        Batch size per gpu: 2
        Accumulated batches: 2
        World size (gpu number): 1
        Required iters per epoch: 100
        Total epochs: 20. Total iters: 2000
22-06-2024 11:38 PM | INFO: Using network [compact].
22-06-2024 11:38 PM | INFO: Using network [unet].
22-06-2024 11:38 PM | INFO: Loss [mssim] enabled.
22-06-2024 11:38 PM | INFO: Loss [PerceptualLoss] enabled.
22-06-2024 11:38 PM | INFO: Loss [GANLoss] enabled.
22-06-2024 11:38 PM | INFO: Loss [colorloss] enabled.
22-06-2024 11:38 PM | INFO: Loss [lumaloss] enabled.
22-06-2024 11:38 PM | INFO: Using model [default].
22-06-2024 11:38 PM | INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 131, in _main
    prepare(preparation_data)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 286, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "D:\AIGC\Net-Train\neosr-new\train.py", line 11, in <module>
    from neosr.data import build_dataloader, build_dataset
  File "D:\AIGC\Net-Train\neosr-new\neosr\data\__init__.py", line 24, in <module>
    _dataset_modules = [importlib.import_module(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AIGC\Net-Train\neosr-new\neosr\data\otf_dataset.py", line 11, in <module>
    from neosr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "D:\AIGC\Net-Train\neosr-new\neosr\data\degradations.py", line 7, in <module>
    from scipy.stats import multivariate_normal
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\__init__.py", line 606, in <module>
    from ._stats_py import *
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\_stats_py.py", line 49, in <module>
    from . import distributions
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\_continuous_distns.py", line 33, in <module>
    import scipy.stats._boost as _boost
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\_boost\__init__.py", line 37, in <module>
    from scipy.stats._boost.nct_ufunc import (
ImportError: DLL load failed while importing nct_ufunc: 页面文件太小，无法完成操作。

**Comment by muslll** [comment]
Hi, please reinstall `scipy`, it looks like some files are missing. One way to make sure your env is the same as the recommended one is by using [poetry](https://python-poetry.org/docs/#installation).

**Comment by linkhins122** [comment]
Thank you for your reply！ after that , I reinstall python3.12 and poetry, and I do use poetry to install neosr. 

Installing the current project: neosr (0.1.0)
PS D:\AIGC\Net-Train\neosr-new> poetry add torch@latest torchvision@latest
Using version ^2.3.1 for torch
Using version ^0.18.1 for torchvision

Updating dependencies
Resolving dependencies... (9.5s)

Package operations: 13 installs, 0 updates, 0 removals

  - Installing intel-openmp (2021.4.0)
  - Installing mpmath (1.3.0)
  - Installing tbb (2021.13.0)
  - Installing filelock (3.15.4)
  - Installing fsspec (2024.6.0)
  - Installing jinja2 (3.1.4)
  - Installing mkl (2021.4.0)
  - Installing sympy (1.12.1)
  - Installing networkx (3.3)
  - Installing typing-extensions (4.12.2)
  - Installing pillow (10.3.0)
  - Installing torch (2.3.1)
  - Installing torchvision (0.18.1),
  
but when i start to train, it report MemoryError again.
Writing lock file
PS D:\AIGC\Net-Train\neosr-new> python train.py -opt train_compact.yml
Path already exists. Renaming it to D:\AIGC\Net-Train\neosr-new\experiments\2xFilm_archived_20240623_142220
Path already exists. Renaming it to D:\AIGC\Net-Train\neosr-new\experiments\tb_logger\2xFilm_archived_20240623_142220
23-06-2024 02:22 PM | INFO:
------------------------ neosr ------------------------
Pytorch Version: 2.3.1+cu121
23-06-2024 02:22 PM | INFO: Dataset [paired] is built.
23-06-2024 02:22 PM | INFO: Training statistics:
        Starting model: 2xFilm
        Number of train images: 200
        Dataset enlarge ratio: 1
        Batch size per gpu: 2
        Accumulated batches: 2
        World size (gpu number): 1
        Required iters per epoch: 100
        Total epochs: 20. Total iters: 2000
23-06-2024 02:22 PM | INFO: Using network [compact].
23-06-2024 02:22 PM | INFO: Using network [unet].
23-06-2024 02:22 PM | INFO: Loss [mssim] enabled.
23-06-2024 02:22 PM | INFO: Loss [PerceptualLoss] enabled.
23-06-2024 02:22 PM | INFO: Loss [GANLoss] enabled.
23-06-2024 02:22 PM | INFO: Loss [colorloss] enabled.
23-06-2024 02:22 PM | INFO: Loss [lumaloss] enabled.
23-06-2024 02:22 PM | INFO: Using model [default].
23-06-2024 02:22 PM | INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 131, in _main
    prepare(preparation_data)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 286, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "D:\AIGC\Net-Train\neosr-new\train.py", line 9, in <module>
    import torch
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\__init__.py", line 1633, in <module>
    from torch import quantization as quantization
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\quantization\__init__.py", line 1, in <module>
    from .quantize import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\quantization\quantize.py", line 10, in <module>
    from torch.ao.quantization.quantize import (
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\ao\quantization\__init__.py", line 3, in <module>
    from .fake_quantize import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\ao\quantization\fake_quantize.py", line 5, in <module>
    from torch.ao.quantization.observer import (
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\ao\quantization\observer.py", line 15, in <module>
    from torch.ao.quantization.utils import (
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\ao\quantization\utils.py", line 12, in <module>
    from torch.fx import Node
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\fx\__init__.py", line 83, in <module>
    from .graph_module import GraphModule
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\fx\graph_module.py", line 19, in <module>
    from .graph import _custom_builtins, _is_from_torch, _PyTreeCodeGen, Graph, PythonCode
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\fx\graph.py", line 4, in <module>
    from . import _pytree as fx_pytree
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\fx\_pytree.py", line 4, in <module>
    import torch.return_types
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\return_types.py", line 48, in <module>
    pytree_register_structseq(_attr)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\return_types.py", line 24, in pytree_register_structseq
    register_pytree_node(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\_pytree.py", line 210, in register_pytree_node
    from . import _cxx_pytree as cxx
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\_cxx_pytree.py", line 37, in <module>
    import optree
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1528, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1502, in _get_spec
MemoryError

My Gpu is 4090 24gb,  cuda drivier is 12.3 windwos11 ......

**Comment by muslll** [comment]
That is strange, first time seeing this. It looks like this is unrelated to neosr though. Your system is failing to import `torch`. I would recommend you update your nvidia driver and then reinstalling torch using the binary compiled against cuda 12.1 (make sure you're inside the poetry env by typing `poetry shell` inside the neosr folder):
```
pip3.12 uninstall torch torchvision
pip3.12 install torch torchvision --index-url https://download.pytorch.org/whl/cu121
```
